name: fitflix-rag
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.1.3
  - requests=2.31.0
  - tqdm=4.66.1
  - pytest=7.4.3
  - pip:
      # Core RAG dependencies
      - chromadb==0.4.18
      - sentence-transformers==2.2.2
      - transformers==4.36.0
      - torch==2.1.0
      - torchvision==0.16.0
      - torchaudio==2.1.0
      
      # LLM and API
      - google-generativeai==0.3.2
      - langchain==0.1.0
      - langchain-community==0.0.10
      
      # Vector store alternatives
      - faiss-cpu==1.7.4
      
      # Document processing
      - pypdf==3.17.0
      - python-docx==1.1.0
      - markdown==3.5.1
      
      # Web interfaces
      - streamlit==1.28.1
      - gradio==4.8.0
      
      # API framework
      - fastapi==0.104.1
      - uvicorn==0.24.0
      
      # Configuration and utilities
      - python-dotenv==1.0.0
      - pydantic==2.5.0
      - pydantic-settings==2.1.0
      
      # Keras compatibility fix
      - tf-keras
      - tensorflow>=2.13.0,<2.16.0
      
      # Additional utilities
      - pathlib
      - typing-extensions